
@startuml CreateUser

state NotLoggedIn{
    
    [*] --> Authenticate

    Authenticate --> Authenticate : Wrong password

}



state LoggedIn{

    Authenticate --> MainMenu : User Logs in

    MainMenu --> EmployeMenu : select Employe

    EmployeMenu --> CreateNewEmployee : select create new
    EmployeMenu --> EmployeMenu : Unautharized employee creation
    EmployeMenu --> MainMenu : Back

    CreateNewEmployee --> EmployeMenu : New employee created
    CreateNewEmployee --> MainMenu : cancel

    CreateNewEmployee : Enter employe details

}


    
LoggedIn --> [*] : user logs out




@enduml


@startuml GetListOfAllBuildings

[*] --> NotLoggedIn

state LoggedIn{

    MainMenu : Options dependant on user type

    MainMenu --> BuildingsMenu : selects

    BuildingsMenu --> MainMenu : Back

    BuildingsMenu --> BuildingsMenu : Select list of all buildings


}

NotLoggedIn --> NotLoggedIn : Wrong password


NotLoggedIn --> MainMenu : User Logs in

LoggedIn --> [*] : user logs out




@enduml