@startuml DataModels

hide empty methods
hide empty members

title DataModels

class EmployeeModel{
    id: int
    **email: str**
    __
    role: str
    password: str
    name: str
    ssn: int
    address: str
    home_phone: int
    mobile_phone: int
    destination: str
}
class ContractorModel{
    id: int
    **phone: str**
    __
    name: str
    contact: str
    opening_hours: str
    destination: str
}
class RealEstateModel{
    id: int
    **real_estate_id: str**
    __
    address: str
    destination_id: str
    maintenance_info: str
}
class ReportModel{
    id: int
    __
    ticket_id: int
    real_estate_id: int
    description: str
    employee_id: str
    destination: str
    total_price: int
    contractor_id: list
    contractor_pay: int
    start_date: str
    close_date: str
    ready: bool
    closed: bool
    comments: list
}
class DestinationModel {
    id: int
    **airport: string**
    __
    country: string
    phone: int
    opening_hours: string
    manager_id: int
}
class TicketModel{
    id: int
    __
    report_id: int
    real_estate_id: int
    description: str
    employee_id: int
    destination: int
    start_date: str
    close_date: str
    priority: str
    open: bool
    is_recurring: bool
}

TicketModel ||-left-o| ReportModel
TicketModel }o-right-|| EmployeeModel
TicketModel }o--|| ContractorModel
TicketModel }o--|| RealEstateModel
TicketModel }o--|| DestinationModel

EmployeeModel ||-left-o{ ReportModel
EmployeeModel }|--|| DestinationModel

ReportModel }o--|| RealEstateModel
ReportModel }o--|| DestinationModel

DestinationModel ||-left-|{ RealEstateModel   

@enduml
