@startuml airline
package airline {
    class ui_layer
    class logic_layer
    class storage_layer
    class manager {
        file_new_employee()
        change_employee()
        file_new_real_estate()
        change_real_estate()
        make_new_work_order()
        change_work_order()
        approve_work_report()
        approve_maintainance_report()
        file_maintainance_schedule()
        change_maintainance_schedule()
        file_contractor()
        change_contractor()
        file_contractor_log()
    }
    class employee {
        name: string
        ssn: int
        address: string
        home_phone: int
        mobile_phone: int
        email: string
        location: string
        --
        login()
        logout()
        file_work_report()
        file_maintainance_report()
        complete_work_order()
        list_employees()
        search_employee()
        list_real_estate()
        search_real_estate()
        search_work_order()
        search_work_report()
        search_contractor()
        list_contractor()
        Search_contractor_log()
        list_contractor_log()
    }
    class destination {
        location: string
        airport: string
        phone: int
        opening_hours: string
        manager: string
    }
    class real_estate {
        location: string
        real_estate_id: int
    }
    class work_order {
        work_order_id: int
        real_estate_id: list
        employees: list
        repeat_project: string
        start_date: string
        importance: string
    }
    class work_report {
        work_report_id: string
        real_estate_id: list
        employees: list
    }
    class maintainance_report {
        maintainance_report_id: string
        real_estate_id: list
        work_decription: string
        repeat_maintainance: string
        employees: list
        price: float
        contractors: list
        contractor_pay: float
        evaluation_by_manager: string
        start_date: string
        time_period: string
    }
    class maintainance_schedule {
        real_estate_id: list
        maintainance_reports: list
        schedule: string
    }
    class contractor {
        contractor_id: int
        name: string
        contact: string
        phone: int
        opening_hours: string
        location: string
    }
    class contractor_log {
        maintainance_report_id: string
        desctiption_of_work: string
        real_estate_id: list
        contractor_id: int
    }
logic_layer -- manager
logic_layer -- employee
logic_layer -- contractor
storage_layer -- real_estate
storage_layer -- destination
storage_layer -- work_order
storage_layer -- work_report
storage_layer -- maintainance_report
storage_layer -- maintainance_schedule
storage_layer -- contractor_log
}
@enduml